import { ArrowUpRight, ArrowUpRight as IncomeIcon, ChevronRight, Circle, CircleCheck, Plus, ReceiptText, Sparkles } from "lucide-react";
import { activePeriod, totalIncome } from "../data/financeSeed";
import { currency, payments, reservedAmount } from "../lib/finance";
import type { Bill } from "../types/finance";

type DashboardPageProps = { bills: Bill[]; greeting: string; openedDateLabel: string; daysUntilNextPayment: number; periodIncome: number; onToggleBill: (id: string) => void; onOpenCalendar: () => void };

export function DashboardPage({ bills, greeting, openedDateLabel, daysUntilNextPayment, periodIncome, onToggleBill, onOpenCalendar }: DashboardPageProps) {
  const reserved = bills.reduce((total, bill) => total + reservedAmount(bill), 0);
  const liquid = totalIncome(activePeriod) - reserved;
  const commitmentPercent = Math.round((reserved / periodIncome) * 100);
  return <div className="page-wrap" id="dashboard">
    <div className="page-heading"><div><p className="eyebrow">{openedDateLabel.toUpperCase()}</p><h1>{greeting}, Leandro.</h1><p className="heading-copy">Aqui está o pulso financeiro das suas contas para o próximo pagamento.</p></div><button className="primary-button"><Plus size={17} />Adicionar movimento</button></div>
    <section className="stats-grid" aria-label="Resumo financeiro">
      <article className="stat-card accent-card"><div className="stat-head"><span>Próximo pagamento</span><span className="status-pill">{daysUntilNextPayment === 0 ? "Hoje" : `Em ${daysUntilNextPayment} dias`}</span></div><strong>{currency.format(periodIncome)}</strong><p>{activePeriod.label} <span>•</span> receita do período</p><div className="progress-track"><span style={{ width: `${commitmentPercent}%` }} /></div><small>{commitmentPercent}% já comprometido</small></article>
      <article className="stat-card"><div className="stat-head"><span>Contas reservadas</span><ReceiptText size={18} /></div><strong>{currency.format(reserved)}</strong><p>de {currency.format(periodIncome)} recebidos</p><div className="stat-footer"><span className="mini-dot peach" />{bills.length} contas previstas</div></article>
      <article className="stat-card"><div className="stat-head"><span>Saldo líquido</span><ArrowUpRight size={18} /></div><strong className="positive">{currency.format(liquid)}</strong><p>disponível após compromissos</p><div className="stat-footer"><span className="mini-dot mint" />+12,4% vs. pagamento anterior</div></article>
    </section>
    <div className="content-grid"><section className="panel payments-panel" id="payments"><div className="panel-heading"><div><p className="eyebrow">FLUXO DE CAIXA</p><h2>Próximos pagamentos</h2></div><button className="text-button" onClick={onOpenCalendar}>Ver calendário <ChevronRight size={15} /></button></div><div className="payment-list">{payments.map((payment) => <div className={payment.status === "next" ? "payment-row next-payment" : "payment-row"} key={payment.date}><div className="date-block"><strong>{payment.date.split(" ")[0]}</strong><span>SET/OUT</span></div><div className="payment-info"><strong>{payment.label}</strong><span>{payment.status === "next" ? "Receita do período" : "Salários + recorrentes"}</span></div><strong className="payment-amount">{currency.format(payment.amount)}</strong><ChevronRight size={17} /></div>)}</div><button className="add-payment"><Plus size={16} />Planejar outro pagamento</button></section>
      <section className="panel goal-panel" id="goals"><div className="goal-orbit"><Sparkles size={20} /></div><p className="eyebrow">OBJETIVO DO MÊS</p><h2>Reserva de emergência</h2><p className="goal-copy">Cada pagamento deixa suas contas um pouco mais tranquilas.</p><div className="goal-value"><strong>{currency.format(780)}</strong><span>de {currency.format(2000)}</span></div><div className="goal-track"><span style={{ width: "39%" }} /></div><div className="goal-footer"><span>39% concluído</span><IncomeIcon size={16} /></div></section></div>
    <section className="panel bills-panel" id="bills"><div className="panel-heading"><div><p className="eyebrow">{activePeriod.label.toUpperCase()}</p><h2>Contas deste pagamento</h2></div><button className="outline-button"><Plus size={16} />Nova conta</button></div><div className="bill-table"><div className="table-head"><span>Conta</span><span>Responsável</span><span>Vencimento</span><span>Valor</span><span>Status</span></div>{bills.map((bill) => <div className="bill-row" key={bill.id}><div className="bill-name"><button className={bill.paid ? "check-control checked" : "check-control"} type="button" aria-label={bill.paid ? `Desmarcar ${bill.name}` : `Marcar ${bill.name} como paga`} onClick={() => onToggleBill(bill.id)}>{bill.paid ? <CircleCheck size={20} /> : <Circle size={20} />}</button><div><strong>{bill.name}</strong><small>{bill.category}</small></div></div><span className="owner-label">{bill.owner}</span><span className="due-label">{bill.due}</span><strong className={bill.paid ? "bill-amount muted" : "bill-amount"}>{currency.format(bill.amount)}</strong><span className={bill.paid ? "bill-status paid" : "bill-status"}>{bill.paid ? "Paga" : "Pendente"}</span></div>)}</div></section>
    <footer className="app-footer"><span>FinanceVault</span><span>Seu dinheiro, no mesmo plano.</span><span>Última sincronização: agora</span></footer>
  </div>;
}
